UrlShortener/UrlShortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("link.urls")),
]

UrlShortener/link/urls.py
from django import urls
from django.urls import path
from .views import home, return_to_orginal

urlpatterns = [
 path('', home, name="home"),   
 path('<str:short_url>/', return_to_orginal, name="redirect"),
]

UrlShortener/link/models.py
from django.db import models
import string
import random

def generate_short_code(length=6):
    characters = string.ascii_letters + string.digits
    return ''.join(random.choices(characters, k=length))

class ShortUrl(models.Model):
    original_url = models.CharField(max_length=200)
    short_url = models.CharField(max_length=10, unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.short_url:
            self.short_url = generate_short_code()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Short url for: {self.original_url} is {self.short_url}"

UrlShortener/link/forms.py
from django import forms
from .models import ShortUrl

class UrlForm(forms.ModelForm):
    class Meta:
        model = ShortUrl
        fields = ['original_url']

UrlShortener/link/views.py
from django.shortcuts import render, redirect
from .models import ShortUrl
from .forms import UrlForm
from django.http import HttpResponseRedirect, Http404
# Create your views here.

def home(request):
    short_url = None
    if request.method == "POST":
        form = UrlForm(request.POST)
        if form.is_valid():
            url_instance = form.save()
            short_url = request.build_absolute_uri(f"/{url_instance.short_url}")
    else:
        form = UrlForm()
    return render(request, "link/home.html", {"form":form, "short_url":short_url})

def return_to_orginal(request, short_url):
    try:
        url = ShortUrl.objects.get(short_url=short_url)
        return HttpResponseRedirect(url.original_url)
    except ShortUrl.DoesNotExist:
        raise Http404("Short Url not found!")

UrlShortener/templates/link/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>URL Shortener</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body class="container mt-5">
    <h1 class="mb-4">Welcome to URL Shortener</h1>

    <form method="POST" novalidate>
        {% csrf_token %}
        <div>
            <label for="id_original_url" class="form-label fw-bold">Enter long URL:</label>
            {{ form.original_url }}
        </div>
        <button type="submit" class="btn btn-primary">Shorten</button>
    </form>

    {% if short_url %}
        <div class="alert alert-success mt-3">
            Short URL: <a href="{{ short_url }}" target="_blank">{{ short_url }}</a>
        </div>
    {% endif %}
</body>
</html>